[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Victor Viola", email = "victor.viola@hvarconsulting.com.br"},
]
dependencies = [
    "langchain",
    "streamlit-authenticator",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

